AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  GetMatches:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Battlefy-League-Stats-Get-Matches"
      CodeUri: src/GetMatches/
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          RIOT_API_KEY: RGAPI-551ff8ea-f663-4d36-a708-a1bbfe739511
      Tags:
        Project: League-Stats
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /matches/{summoner}
            Method: GET
            RestApiId: !Ref RESTApi

  RESTApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "League-Stats-REST-Api"
      StageName: "dev"
      EndpointConfiguration:
        Type: Regional
      Tags:
        Project: League-Stats
      Models:
        ValidatorModel:
          $schema: "http://json-schema.org/draft-04/schema#"
          properties:
            base:
              type: string
          type: object

  Default5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref RESTApi

  Default4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref RESTApi
